codecov:
  token: 419d06f8-879f-4160-b901-a8bce09b55b3
  branch: master
  bot: null
coverage:
  precision: 2
  round: down
  range: "70...100"
  notify:
    webhook:
      _custom_:
        url: null
        threshold: null
        branches: null
        only_pulls: null
  status:
    project:
      default:
        target: auto
        threshold: null
        branches: null
    patch:
      default:
        target: auto
        branches: null
    changes:
      default:
        branches: null
comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
  behavior: default